[Rainmeter]
Update=5000
AccurateText=1

[Metadata]
Name=Dash
Author= borsTiHD
Information= A Rainmeter skin collection for people with too many screens and a need for some clean system monitoring tools and other various widgets.
Version= 1.0
License= CC BY-NC

;-- Load in the variables from file --
[Variables]
@include=../Variables.inc
TempPath=D:\Stuff\iCUE\
InFile=#TempPath#corsair_cue_20220310_08_00_40.csv
OutFile=#TempPath#logCopy.csv

[Background]
;This is only used to get the same border width around the entire widget, it does not have any other visual purpose except this.
Meter=Shape
Shape=Rectangle 0,0,470,290 | Fill Color 0,0,0,0 | StrokeWidth 0

;------------------------
;--------PLUGINS---------
;------------------------

[FrostedGlass]
Measure=Plugin
Plugin=FrostedGlass
Type=Acrylic
Corner=Round

;------------------------
;-------MEASURES---------
;------------------------

[measureICUELogCopy]
Measure=Plugin
Plugin=RunCommand
Parameter=copy "#InFile#" "#OutFile#"
DynamicVariables=1

[measureICUEParent]
Measure=WebParser
URL=file://#OutFile#
RegExp=(?si)^.*\n(.*),(.*)°C,(.*)RPM,(.*)RPM,(.*)RPM,(.*)RPM(.*)$
DynamicVariables=1
UpdateRate=1

[measureFAN1]
Measure=WebParser
URL=[measureICUEParent]
StringIndex=3
MinValue=700
MaxValue=5400

[measureFAN2]
Measure=WebParser
URL=[measureICUEParent]
StringIndex=4
MinValue=700
MaxValue=5400

[measureFAN3]
Measure=WebParser
URL=[measureICUEParent]
StringIndex=5
MinValue=700
MaxValue=5400

[measurePUMPfan]
Measure=WebParser
URL=[measureICUEParent]
StringIndex=6
MinValue=700
MaxValue=5400

[measureWaterTempString]
Measure=WebParser
URL=[measureICUEParent]
StringIndex=2

[measureWaterTemp]
Measure=Calc
Formula=[measureWaterTempString]
DynamicVariables=1


;--------------------------------------------------------
;-------------------------------------------------------- Title
;--------------------------------------------------------

[iCUEtitle]
Meter=String
FontFace=#Font#
Text=iCUE: H150i RGB PRO XT
FontColor=#textColorDark#
FontSize=15
Antialias=1
X=20
Y=20

;--------------------------------------------------------
;-------------------------------------------------------- PUMP / FANs
;--------------------------------------------------------


;-------PUMP---------
[PUMPfanRPMcirclebg]
Meter=Roundline
X=60
Y=100
StartAngle=(Rad(270))
RotationAngle=(Rad(360))
LineStart=30
LineLength=40
LineColor=0,0,0,100
Solid=1
AntiAlias=1

[PUMPfanRPMcircle]
Meter=Roundline
MeasureName=measurePUMPfan
X=0r
Y=0r
StartAngle=(Rad(270))
RotationAngle=(Rad(360))
LineStart=30
LineLength=40
LineColor=255,255,255,100
Solid=1
AntiAlias=1

[PUMPfanRPM]
Meter=String
MeasureName=measurePUMPfan
FontFace=#Font#
FontColor=255,255,255
FontSize=8
StringAlign=CenterCenter
Antialias=1
Text=%1 rpm
X=0r
Y=-5r

[PUMPfanText]
Meter=String
FontFace=#Font#
FontColor=#textColorDark#
FontSize=8
StringAlign=CenterCenter
Antialias=1
Text=PUMP
X=0r
Y=15r

;-------FAN1---------
[FAN1fanRPMcirclebg]
Meter=Roundline
X=90r
Y=-10r
StartAngle=(Rad(270))
RotationAngle=(Rad(360))
LineStart=30
LineLength=40
LineColor=0,0,0,100
Solid=1
AntiAlias=1

[FAN1fanRPMcircle]
Meter=Roundline
MeasureName=measureFAN1
X=0r
Y=0r
StartAngle=(Rad(270))
RotationAngle=(Rad(360))
LineStart=30
LineLength=40
LineColor=255,255,255,100
Solid=1
AntiAlias=1

[FAN1fanRPM]
Meter=String
MeasureName=measureFAN1
FontFace=#Font#
FontColor=255,255,255
FontSize=8
StringAlign=CenterCenter
Antialias=1
Text=%1 rpm
X=0r
Y=-5r

[FAN1fanText]
Meter=String
FontFace=#Font#
FontColor=#textColorDark#
FontSize=8
StringAlign=CenterCenter
Antialias=1
Text=FAN1
X=0r
Y=15r

;-------FAN2---------
[FAN2fanRPMcirclebg]
Meter=Roundline
X=90r
Y=-10r
StartAngle=(Rad(270))
RotationAngle=(Rad(360))
LineStart=30
LineLength=40
LineColor=0,0,0,100
Solid=1
AntiAlias=1

[FAN2fanRPMcircle]
Meter=Roundline
MeasureName=measureFAN2
X=0r
Y=0r
StartAngle=(Rad(270))
RotationAngle=(Rad(360))
LineStart=30
LineLength=40
LineColor=255,255,255,100
Solid=1
AntiAlias=1

[FAN2fanRPM]
Meter=String
MeasureName=measureFAN2
FontFace=#Font#
FontColor=255,255,255
FontSize=8
StringAlign=CenterCenter
Antialias=1
Text=%1 rpm
X=0r
Y=-5r

[FAN2fanText]
Meter=String
FontFace=#Font#
FontColor=#textColorDark#
FontSize=8
StringAlign=CenterCenter
Antialias=1
Text=FAN2
X=0r
Y=15r

;-------FAN3---------
[FAN3fanRPMcirclebg]
Meter=Roundline
X=90r
Y=-10r
StartAngle=(Rad(270))
RotationAngle=(Rad(360))
LineStart=30
LineLength=40
LineColor=0,0,0,100
Solid=1
AntiAlias=1

[FAN3fanRPMcircle]
Meter=Roundline
MeasureName=measureFAN3
X=0r
Y=0r
StartAngle=(Rad(270))
RotationAngle=(Rad(360))
LineStart=30
LineLength=40
LineColor=255,255,255,100
Solid=1
AntiAlias=1

[FAN3fanRPM]
Meter=String
MeasureName=measureFAN3
FontFace=#Font#
FontColor=255,255,255
FontSize=8
StringAlign=CenterCenter
Antialias=1
Text=%1 rpm
X=0r
Y=-5r

[FAN3fanText]
Meter=String
FontFace=#Font#
FontColor=#textColorDark#
FontSize=8
StringAlign=CenterCenter
Antialias=1
Text=FAN3
X=0r
Y=15r

;--------------------------------------------------------
;-------------------------------------------------------- WATER TEMP
;--------------------------------------------------------


[MeterBackgroundTEMP]
Meter=Image
X=30
Y=170
W=410
H=90
SolidColor=255,255,255,30

[LineGraphTEMP]
Meter=Line
MeasureName=measureWaterTemp
LineColor=255,255,255
HorizontalLines=1
LineCount=2
UpdateDivider=1
HorizontalLineColor=255,255,255,100
AntiAlias=1
X=0r
Y=0r
W=410
H=90

[GraphTEMPkey]
Meter=String
FontFace=#Font#
FontColor=255,255,255
FontSize=10
StringAlign=LeftCenter
Antialias=1
Text=WATER TEMP:
X=10r
Y=100r

[TEMPText]
Meter=String
MeasureName=measureWaterTemp
FontFace=#Font#
FontColor=#textColorDark#
FontSize=10
StringAlign=LeftCenter
Antialias=1
Text=%1
X=90r
Y=0r

[Graph0scale]
Meter=String
FontFace=#Font#
FontColor=255,255,255
FontSize=9
StringAlign=LeftCenter
Antialias=1
Text=0
X=-110r
Y=-10r

[Graph100scale]
Meter=String
FontFace=#Font#
FontColor=255,255,255
FontSize=9
StringAlign=LeftCenter
Antialias=1
Text=100
X=-13r
Y=-90r
