[Rainmeter]
Update=2000
AccurateText=1

[Metadata]
Name=Dash
Author= Mazeby
Information= A Rainmeter skin collection for people with too many screens and a need for some clean system monitoring tools and other various widgets.
Version= 1.0
License= CC BY-NC 

;NOTE!
;THIS WIDGET REQUIRES MSI AFTERBURNER 4.5 AND RIVA TUNER STATISTICS SERVER 7.1 IN ORDER TO FUNCTION PROPERLY!
;THE BEFORE MENTIONED PROGRAMS MUST RUN IN THE BACKGROUND THE ENTIRE TIME YOU WANT TO USE THIS WIDGET!

;-- Load in the variables from file --
[Variables]
@include=../Variables.inc

[Background]
;This is only used to get the same border width around the entire widget, it does not have any other visual purpose except this.
Meter=Shape
Shape=Rectangle 0,0,910,340 | Fill Color 0,0,0,0 | StrokeWidth 0

;------------------------
;--------PLUGINS---------
;------------------------

[FrostedGlass]
Measure=Plugin
Plugin=FrostedGlass
Type=Acrylic
Corner=Round

;------------------------
;-------MEASURES---------
;------------------------

[measureGPUusage]
Measure=Plugin
Plugin=HWiNFO.dll
HWiNFOSensorId=#HWiNFO-GPU0-SensorId#
HWiNFOSensorInstance=#HWiNFO-GPU0-SensorInstance#
HWiNFOEntryId=#HWiNFO-GPU0-Usage#
HWiNFOType=CurrentValue
MinValue=0
MaxValue=100
IfCondition=(measureGPUusage < #YellowStarts#)
IfTrueAction=[!SetVariable GPUloadColor #GreenColor#]
IfCondition2=(measureGPUusage >= #YellowStarts#) && (measureGPUusage < #RedStarts#)
IfTrueAction2=[!SetVariable GPUloadColor #YellowColor#]
IfCondition3=(measureGPUusage >= #RedStarts#)
IfTrueAction3=[!SetVariable GPUloadColor #RedColor#]

[measureGPUpower]
Measure=Plugin
Plugin=HWiNFO.dll
HWiNFOSensorId=#HWiNFO-GPU0-SensorId#
HWiNFOSensorInstance=#HWiNFO-GPU0-SensorInstance#
HWiNFOEntryId=#HWiNFO-GPU0-Power#
HWiNFOType=CurrentValue

[measureGPUname]
Measure=Registry
RegHKey=HKEY_LOCAL_MACHINE
RegKey=SOFTWARE\Microsoft\Windows NT\CurrentVersion\WinSat
RegValue=PrimaryAdapterString

[getGPURAM]
Measure=Calc
Formula=#HWiNFO-GPU0-VRAMMemoryTotal#
UpdateDivider=-1

[measureGPURAM]
Measure=Calc
Formula=(getGPURAM / 1024)

[measureGPUVRAMusage]
Measure=Plugin
Plugin=HWiNFO.dll
HWiNFOSensorId=#HWiNFO-GPU0-SensorId#
HWiNFOSensorInstance=#HWiNFO-GPU0-SensorInstance#
HWiNFOEntryId=#HWiNFO-GPU0-VRAMUsage#
HWiNFOType=CurrentValue

[measureGPUVRAMusagePct]
Measure=Calc
Formula=(Clamp(measureGPUVRAMusage / getGPURAM * 100, 0, 100))
MinValue=0
MaxValue=100
IfCondition=(measureGPUVRAMusagePct < #YellowStarts#)
IfTrueAction=[!SetVariable VRAMColor #GreenColor#]
IfCondition2=(measureGPUVRAMusagePct >= #YellowStarts#) && (measureGPUVRAMusagePct < #RedStarts#)
IfTrueAction2=[!SetVariable VRAMColor #YellowColor#]
IfCondition3=(measureGPUVRAMusagePct >= #RedStarts#)
IfTrueAction3=[!SetVariable VRAMColor #RedColor#]

[measureGPUfanSpeed]
Measure=Plugin
Plugin=HWiNFO.dll
HWiNFOSensorId=#HWiNFO-GPU0-SensorId#
HWiNFOSensorInstance=#HWiNFO-GPU0-SensorInstance#
HWiNFOEntryId=#HWiNFO-GPU0-Fan0#
HWiNFOType=CurrentValue
MinValue=0
MaxValue=100
;Measure=Plugin
;Plugin=Plugins\MSIAfterburner.dll
;DataSource=Fan speed
;MinValue=0
;MaxValue=100
IfCondition=(measureGPUfanSpeed < #YellowStarts#)
IfTrueAction=[!SetVariable FanSpeedColor #GreenColor#]
IfCondition2=(measureGPUfanSpeed >= #YellowStarts#) && (measureGPUfanSpeed < #RedStarts#)
IfTrueAction2=[!SetVariable FanSpeedColor #YellowColor#]
IfCondition3=(measureGPUfanSpeed >= #RedStarts#)
IfTrueAction3=[!SetVariable FanSpeedColor #RedColor#]

[measureGPUTemp]
Measure=Plugin
Plugin=HWiNFO.dll
HWiNFOSensorId=#HWiNFO-GPU0-SensorId#
HWiNFOSensorInstance=#HWiNFO-GPU0-SensorInstance#
HWiNFOEntryId=#HWiNFO-GPU0-Temp#
HWiNFOType=CurrentValue
MinValue=0
MaxValue=200

[measureGPUcoreClock]
Measure=Plugin
Plugin=HWiNFO.dll
HWiNFOSensorId=#HWiNFO-GPU0-SensorId#
HWiNFOSensorInstance=#HWiNFO-GPU0-SensorInstance#
HWiNFOEntryId=#HWiNFO-GPU0-CoreClock#
HWiNFOType=CurrentValue
;Measure=Plugin
;Plugin=Plugins\MSIAfterburner.dll
;DataSource=Core clock

[measureGPUmemoryClock]
Measure=Plugin
Plugin=HWiNFO.dll
HWiNFOSensorId=#HWiNFO-GPU0-SensorId#
HWiNFOSensorInstance=#HWiNFO-GPU0-SensorInstance#
HWiNFOEntryId=#HWiNFO-GPU0-VRAMClock#
HWiNFOType=CurrentValue
;Measure=Plugin
;Plugin=Plugins\MSIAfterburner.dll
;DataSource=Memory clock

;------------------------------------------------------------------------------------------------------------------
;------------------------------------------------------------------------------------------------------------------GPU Monitoring
;------------------------------------------------------------------------------------------------------------------

[GPUtitle]
Meter=String
MeasureName=measureGPUname
MeasureName2=measureGPURAM
MeasureName3=measureGPUpower
FontFace=#Font#
Text=GPU: %1 | %2 GB VRAM | %3 Watt
FontColor=#textColorDark#
FontSize=15
Antialias=1
X=20
Y=20


;--------------------------------------------------------
;--------------------------------------------------------GPU Load
;--------------------------------------------------------

[GPUtext]
Meter=String
FontFace=#Font#
FontColor=255,255,255
FontSize=12
StringAlign=CenterCenter
Antialias=1
Text=GPU
X=140
Y=310

[GPUload%]
Meter=String
MeasureName=measureGPUusage
FontFace=#Font#
FontColor=255,255,255
FontSize=20
StringAlign=CenterCenter
Antialias=1
Text=%1%
X=140
Y=180

[GPUloadcirclebg]
Meter=Roundline
X=140
Y=180
StartAngle=(Rad(270))
RotationAngle=(Rad(360))
LineStart=60
LineLength=110
LineColor=0,0,0,100
Solid=1
AntiAlias=1

[GPUloadcircle]
Meter=Roundline
MeasureName=measureGPUusage
X=140
Y=180
StartAngle=(Rad(270))
RotationAngle=(Rad(360))
LineStart=60
LineLength=110
LineColor=[#GPUloadColor]
Solid=1
AntiAlias=1
DynamicVariables=1


;--------------------------------------------------------
;--------------------------------------------------------VRAM usage
;--------------------------------------------------------

[VRAMtext]
Meter=String
FontFace=#Font#
FontColor=255,255,255
FontSize=12
StringAlign=CenterCenter
Antialias=1
Text=VRAM
X=360
Y=185

[VRAM%]
Meter=String
MeasureName=measureGPUVRAMusagePct
FontFace=#Font#
FontColor=255,255,255
FontSize=15
StringAlign=CenterCenter
Antialias=1
Text=%1%
X=360
Y=120

[VRAMcirclebg]
Meter=Roundline
X=360
Y=120
StartAngle=(Rad(270))
RotationAngle=(Rad(360))
LineStart=40
LineLength=50
LineColor=0,0,0,100
Solid=1
AntiAlias=1

[VRAMcircle]
Meter=Roundline
MeasureName=measureGPUVRAMusagePct
X=360
Y=120
StartAngle=(Rad(270))
RotationAngle=(Rad(360))
LineStart=40
LineLength=50
LineColor=[#VRAMColor]
Solid=1
AntiAlias=1
DynamicVariables=1


;--------------------------------------------------------
;--------------------------------------------------------Core Clock
;--------------------------------------------------------

[CoreClockCircleBg]
Meter=Shape
Shape=Ellipse 0,0,50 | Fill Color 0,0,0,100 | StrokeWidth 0
AntiAlias=1
X=600
Y=120

[CoreClockText]
Meter=String
FontFace=#Font#
FontColor=255,255,255
FontSize=12
StringAlign=CenterCenter
Antialias=1
Text=Core Clock
X=600
Y=185

[CoreClock%]
Meter=String
MeasureName=measureGPUCoreClock
FontFace=#Font#
FontColor=255,255,255
FontSize=20
StringAlign=CenterCenter
Antialias=1
Text=%1
X=600
Y=120

[CoreClockMHz]
Meter=String
FontFace=#Font#
FontColor=255,255,255
FontSize=15
StringAlign=CenterCenter
Antialias=1
Text=MHz
X=600
Y=145


;--------------------------------------------------------
;--------------------------------------------------------VRAM Clock
;--------------------------------------------------------

[MemoryClockCircleBg]
Meter=Shape
Shape=Ellipse 0,0,50 | Fill Color 0,0,0,100 | StrokeWidth 0
AntiAlias=1
X=720
Y=120

[MemoryClockText]
Meter=String
FontFace=#Font#
FontColor=255,255,255
FontSize=12
StringAlign=CenterCenter
Antialias=1
Text=VRAM Clock
X=720
Y=185

[MemoryClock%]
Meter=String
MeasureName=measureGPUmemoryClock
FontFace=#Font#
FontColor=255,255,255
FontSize=20
StringAlign=CenterCenter
Antialias=1
Text=%1
X=720
Y=120

[MemoryClockMHz]
Meter=String
FontFace=#Font#
FontColor=255,255,255
FontSize=15
StringAlign=CenterCenter
Antialias=1
Text=MHz
X=720
Y=145


;--------------------------------------------------------
;--------------------------------------------------------GPU & VRAM Graph
;--------------------------------------------------------

[MeterBackground1]
Meter=Image
X=310
Y=200
W=460
H=90
SolidColor=255,255,255,30

[LineGraphGPUVRAM]
Meter=Line
MeasureName=measureGPUusage
MeasureName2=measureGPUVRAMusagePct
LineColor=255,255,255
LineColor2=255,255,255,100
HorizontalLines=1
LineCount=2
UpdateDivider=1
HorizontalLineColor=255,255,255,100
AntiAlias=1
X=310
Y=200
W=460
H=90

[GraphGPUkey]
Meter=String
FontFace=#Font#
FontColor=255,255,255
FontSize=10
StringAlign=LeftCenter
Antialias=1
Text=GPU
X=310
Y=300

[GraphVRAMkey]
Meter=String
FontFace=#Font#
FontColor=#textColorDark#
FontSize=10
StringAlign=LeftCenter
Antialias=1
Text=VRAM
X=345
Y=300

[Graph0scale]
Meter=String
FontFace=#Font#
FontColor=255,255,255
FontSize=9
StringAlign=LeftCenter
Antialias=1
Text=0
X=300
Y=290

[Graph100scale]
Meter=String
FontFace=#Font#
FontColor=255,255,255
FontSize=9
StringAlign=LeftCenter
Antialias=1
Text=100
X=287
Y=200

;--------------------------------------------------------
;--------------------------------------------------------Fan Speed
;--------------------------------------------------------
[FanSpeedtext]
Meter=String
FontFace=#Font#
FontColor=255,255,255
FontSize=12
StringAlign=CenterCenter
Antialias=1
Text=Fan Speed
X=480
Y=185

[FanSpeed%]
Meter=String
MeasureName=measureGPUfanSpeed
FontFace=#Font#
FontColor=255,255,255
FontSize=15
StringAlign=CenterCenter
Antialias=1
Text=%1%
X=480
Y=120

[FanSpeedcirclebg]
Meter=Roundline
X=480
Y=120
StartAngle=(Rad(270))
RotationAngle=(Rad(360))
LineStart=40
LineLength=50
LineColor=0,0,0,100
Solid=1
AntiAlias=1

[FanSpeedcircle]
Meter=Roundline
MeasureName=measureGPUfanSpeed
X=480
Y=120
StartAngle=(Rad(270))
RotationAngle=(Rad(360))
LineStart=40
LineLength=50
LineColor=[#FanSpeedColor]
Solid=1
AntiAlias=1
DynamicVariables=1

;--------------------------------------------------------
;--------------------------------------------------------Framerate
;--------------------------------------------------------

[FramerateCircleBg]
Meter=Shape
Shape=Ellipse 0,0,50 | Fill Color 0,0,0,100 | StrokeWidth 0
AntiAlias=1
X=840
Y=120

[GPUTempText]
Meter=String
FontFace=#Font#
FontColor=255,255,255
FontSize=12
StringAlign=CenterCenter
Antialias=1
Text=Temperatur
X=840
Y=185

[GPUTemp]
Meter=String
MeasureName=measureGPUTemp
FontFace=#Font#
FontColor=255,255,255
FontSize=20
StringAlign=CenterCenter
Antialias=1
;Text=%1
X=840
Y=120

[GPUCelcius]
Meter=String
FontFace=#Font#
FontColor=255,255,255
FontSize=15
StringAlign=CenterCenter
Antialias=1
Text="°C"
X=840
Y=145

[MeterBackground]
Meter=Image
X=790
Y=200
W=100
H=90
SolidColor=255,255,255,30

[LineGraphGPUTemp]
Meter=Line
MeasureName=measureGPUTemp
UpdateDivider=1
HorizontalLineColor=255,255,255,100
AntiAlias=1
X=790
Y=200
W=100
H=90

